update cdk env for build
Signed-off-by: Sébastien Allamand <sallaman@amazon.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,21 +1,24 @@
 # ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
 
-name: upgrade
+name: build
 on:
+  pull_request: {}
   workflow_dispatch: {}
-  schedule:
-    - cron: 0 0 * * *
 jobs:
-  upgrade:
-    name: Upgrade
+  build:
     runs-on: ubuntu-latest
     permissions:
-      contents: read
+      contents: write
     outputs:
-      patch_created: ${{ steps.create_patch.outputs.patch_created }}
+      self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
+    env:
+      CI: "true"
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Setup Mock AWS Context
         run: |-
           echo "CDK_DEFAULT_ACCOUNT=123456789012" >> $GITHUB_ENV
@@ -29,34 +32,43 @@ jobs:
         with:
           node-version: 20.x
       - name: Install dependencies
-        run: yarn install --check-files --frozen-lockfile
-      - name: Upgrade dependencies
-        run: npx projen upgrade
+        run: yarn install --check-files
+      - name: build
+        run: npx projen build
       - name: Find mutations
-        id: create_patch
+        id: self_mutation
         run: |-
           git add .
-          git diff --staged --patch --exit-code > .repo.patch || echo "patch_created=true" >> $GITHUB_OUTPUT
+          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT
         working-directory: ./
       - name: Upload patch
-        if: steps.create_patch.outputs.patch_created
+        if: steps.self_mutation.outputs.self_mutation_happened
         uses: actions/upload-artifact@v4
         with:
           name: .repo.patch
           path: .repo.patch
           overwrite: true
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat .repo.patch
+          exit 1
     container:
       image: jsii/superchain:1-buster-slim-node18
-  pr:
-    name: Create Pull Request
-    needs: upgrade
+  self-mutation:
+    needs: build
     runs-on: ubuntu-latest
     permissions:
-      contents: read
-    if: ${{ needs.upgrade.outputs.patch_created }}
+      contents: write
+    if: always() && needs.build.outputs.self_mutation_happened && !(github.event.pull_request.head.repo.full_name != github.repository)
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Download patch
         uses: actions/download-artifact@v4
         with:
@@ -68,32 +80,10 @@ jobs:
         run: |-
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
-      - name: Create Pull Request
-        id: create-pr
-        uses: peter-evans/create-pull-request@v6
-        with:
-          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
-          commit-message: |-
-            chore(deps): upgrade dependencies
-
-            Upgrades project dependencies. See details in [workflow run].
-
-            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-
-            ------
-
-            *Automatically created by projen via the "upgrade" workflow*
-          branch: github-actions/upgrade
-          title: "chore(deps): upgrade dependencies"
-          labels: auto-approve,auto-merge
-          body: |-
-            Upgrades project dependencies. See details in [workflow run].
-
-            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-
-            ------
-
-            *Automatically created by projen via the "upgrade" workflow*
-          author: github-actions <github-actions@github.com>
-          committer: github-actions <github-actions@github.com>
-          signoff: true
+      - name: Push changes
+        env:
+          PULL_REQUEST_REF: ${{ github.event.pull_request.head.ref }}
+        run: |-
+          git add .
+          git commit -s -m "chore: self mutation"
+          git push origin HEAD:$PULL_REQUEST_REF
